### PR TITLE
Adding getTransactions

### PR DESCRIPTION
**Pull request by redcap3000**
Adding this (getTransactions) much needed function to the node library. Its unknown why this is missing, as it is only a few lines of code to implement. Please merge this; many have been asking for this for years.

### CODE REVIEW

**Comment by knoxcard** [comment]
that looks pretty darn good, C'mon Coinbase, merge, merge, merge!

**Comment by redcap3000** [comment]
In my dreams!

**Comment by knoxcard** [comment]
I guess they added their own version, it's on the README page, is this the same thing?

```
Using pagination

account.getTransactions(null, function(err, txns, pagination) {
  txns.forEach(function(txn) {
    console.log('my txn: ' + txn.id);
  });
  console.log(pagination.next_uri);
  account.getTransactions(pagination, function(err, txns) {
    txns.forEach(function(txn) {
      console.log('my txn: ' + txn.id);
    });
  });
});
```

**Comment by redcap3000** [comment]
I'm pretty confident the code example wasn't working... or that code is not present; hence this merge request from 9+ months ago. The only changes to this repo are version numbers for the past year or longer.

**Comment by knoxcard** [comment]
What a crying shame, if the code indeed does not operate correctly.  I installed this module and got the first example to work, retrieving balances.  Hopefully within the next week or so, I'll be able to get my hands dirty.

**Comment by redcap3000** [comment]
It was kind of halfway completed. Very simple fix; copied and pasted a similar function, uncommented some variables. This is all we can do. Bring attention to this PR and maybe someone at coinbase will give the nodejs community some attention.

**Comment by knoxcard** [comment]
That's the beauty of open source, in that we can just move forward without others says so.  Although, it would help considerably if they did merge the code, as thousands of developers woud be able to (test/implement/enhance/fix/optimize) what you've developed as opposed to lets say you, me and eight other developers.  The more developers in, the faster we progress as a whole.

**Comment by knoxcard** [comment]
Seriously, considering how large of a company Coinbase is and the enormous sums of cash they have, this module should be updated once every two days! I find it completely ABSURD! The last commit was in April??? How many ICO's and new crypto coins have come out since April? lol  I see Coinbase added a few measly coins too after yearrrrrrrss have passed by,  Binance has like what, a 100+??  haha.

**Comment by redcap3000** [comment]
Preaching to the choir buddy. Copied pasted, done. Probably 15 minutes spent. Story of my life.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.

**Pull request closed without merging**
